### ISSUE TITLE
Strange answer from Llama2-7b-int4

### ISSUE THREAD

**Issue by kiddjacky** [sophgo/Llama2-TPU#3]
After downloading the bmodel from baidu, I get the llama2-7b-int4 running. however, the results are strange. No matter what Question I asked, it seems the answer start with "Unterscheidung between" and misunderstood the question. I would like to know if the weight I have downloaded is broken or the binary I compiled has something wrong(I compile the soc/demo/demo.cpp)

Question: hello, what's your name?

Answer:
 Unterscheidung between "hello" and "hi"

Question:

Answer:  Unterscheidung between the two types of memory
 Unterscheidung between the two types of memory

Introduction:

Memory is a crucial cognitive function that enables us to store and retrieve information. There are two main types of memory: sensory memory and working memory. In this essay, we will explore the differences between these two types of memory, including their functions, duration, capacity, and the processes involved in their operation.

**Comment by WaitDumplings** [comment]
This issue has been resolved. Please pull the latest code
